# Generated by Django 4.1 on 2024-01-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_patientprofile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
